### ISSUE TITLE
$odoo->login(); return blank screen

### ISSUE THREAD

**Issue by varinderkaur** [MohammedRashad/Odoo-REST-API#3]
Hi Mohammed,
   I need your help. When I call login function in index.php it returns nothing. I don't understand What is an array() in this function:- **_$this->user_id = $this->common->authenticate($this->db, $this->username, $this->password, array());_**
can you explain me this?

**Comment by MohammedRashad** [comment]
this application authenticates with an old version of the Odoo API (Odoo 9) 
this one unfortunately is deprecated now .

so I can't help you alot.
can you help me and update it ?

**Comment by varinderkaur** [comment]
I got the solution. Actually I'm putting wrong credentials of username and password, I thought It was Database username and password but in actual it was User's login credentials.
